#!/usr/bin/env python

import sys
import os


def pdfcrop(filenames):
    for fname in filenames:
        os.system("pdfcrop {0} {0}".format(fname))


if __name__ == "__main__":
    pdfcrop(sys.argv[1:])
